<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WorkflowDesigner\WorkflowDesigner.csproj" />
    <ProjectReference Include="..\..\samples\WorkflowRuntime.SampleActionPlugin\WorkflowRuntime.SampleActionPlugin.csproj" />
    <PackageReference Include="WorkflowCore" Version="$(WorkflowVersion)" />
    <PackageReference Include="WorkflowWpfSdk" Version="$(WorkflowVersion)" />
    <ProjectReference Include="..\..\samples\WorkflowRuntime.OpenCvSamplePlugin\WorkflowRuntime.OpenCvSamplePlugin.csproj" />
  </ItemGroup>
</Project>
